### ISSUE TITLE
New Rule: ARIA attributes must contain valid values 

### ISSUE THREAD

**Issue by jkodu** [auto-wcag/auto-wcag#193] opened 2018-07-30 08:41 UTC
---
name:
description: |
  This rule checks that ARIA attributes contains valid values

success_criterion:
- 4.1.2 # Name, Role, Value

test_aspects:
- DOM Tree

authors:
- Anne Thyme Nørregaard
---

### Applicability

The rule applies to any WAI-ARIA attribute.

### Expectation (1)

Each target element has a valid value according to the [value type](https://www.w3.org/TR/wai-aria-1.1/#propcharacteristic_value) for the given state or property as specified by [WAI-ARIA](https://www.w3.org/TR/wai-aria).

## Assumptions

*There are currently no assumptions*

## Accessibility support

There are no major accessibility support issues known for this rule.

## Background

-  (https://www.w3.org/TR/wai-aria-1.1/#propcharacteristic_value)

### Pass example 1

Description...

```html
<!-- code -->
```

### Pass example 2

...

### Failure example 1

Description...

```html
<!-- code -->
```

### Failure example 2

...

### Inapplicable example 1

Description...

```html
<!-- code -->
```

### Inapplicable example 2

...

**Comment by annethyme** [comment] 2018-08-27 07:55
Duplicate of https://github.com/auto-wcag/auto-wcag/issues/176

**Closed by annethyme** 2018-08-27 07:55 UTC
